config/routes.rb
Rails.application.routes.draw do

  resources :cats

  resources :cat_rental_requests, only: [:show, :new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end


end

app/models/cat.rb
class Cat < ActiveRecord::Base

  validates :birth_date, :name, presence: true
  validates :sex, presence: true, inclusion: { in: %w(M F) }
  validates :color, presence: true, inclusion: { in: %w(Orange Black White Brown Calico Grey) }

  has_many :rental_requests,
    -> { order(start_date: :asc) },
    dependent: :destroy,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest


  def age
    t = Time.now
    diff = t.to_i - birth_date.to_time.to_i
    diff / (31536000)
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validate :start_date_before_end_date
  validate :no_rental_overlap

  belongs_to :cat
  delegate :name, to: :cat, prefix: true

  def approve!
    CatRentalRequest.transaction do
      self.status = "APPROVED"
      self.save
    end
  end

  def deny!
    self.status = "DENIED"
    self.save
  end

  def pending?
    status == "PENDING"
  end

  def no_rental_overlap
    unless overlapping_approved_requests.empty?
      errors[:cat_rental] << "overlaps another rental"
    end
  end

  def overlapping_requests
    requests = CatRentalRequest.where(cat_id: cat_id)

    overlapping = []
    requests.each do |request|
      next if self.id == request.id
      request_start = request.start_date
      request_end = request.end_date
      if (self.start_date > request_start && self.start_date < request_end) ||
         (self.start_date < request_start && self.end_date > request_start)
        overlapping << request
      end
    end

    overlapping
  end

  def overlapping_approved_requests
    overlapping_requests.select { |request| request.status == "APPROVED" }
  end

  def start_date_before_end_date
    unless start_date < end_date
      errors[:start_date] << "cannot be after end date"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def render_errors(obj)
    render text: obj.errors.full_messages, status: :unprocessable_entity
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def create
    @rental_request = CatRentalRequest.new(rental_request_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      render_errors(@rental_request)
    end
  end

  def new
    @cats = Cat.all
    render :new
  end

  def approve

    @rental_request = CatRentalRequest.find_by(id: params[:id])
    if @rental_request.approve!
      redirect_to cat_url(@rental_request.cat)
    else
      render :deny
    end
  end

  def deny
    @rental_request = CatRentalRequest.find_by(id: params[:id])
    @rental_request.deny!
    redirect_to cat_url(@rental_request.cat)
  end

  private

  def rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    render :show
  end

  def new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render_errors(@cat)
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render_errors(@cat)
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:birth_date, :color, :name, :sex, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h2>Request to rent a cat</h2>

<form action= "<%= cat_rental_requests_url %>" method="post">
  <label for="cat_id">Choose a Cat </label>
  <select id="cat_id" name="cat_rental_request[cat_id]">
    <option disabled selected>--Please Select--</option>
    <% @cats.each do |cat| %>
      <option value= "<%= cat.id %>"><%= cat.name %></option>
    <% end %>
  </select>

  <br>
  <br>

  <label for="start-date">Start Date</label>
  <input id="start-date" type="date" name="cat_rental_request[start_date]">

  <br>
  <br>

  <label for="end-date">End Date</label>
  <input id="end-date" type="date" name="cat_rental_request[end_date]">

  <br>
  <br>

  <%= button_to 'Place Request', cat_rental_requests_url %>
</form>

app/views/cat_rental_requests/show.html.erb
<h2>Your Rental Request for <%= @rental_request.cat_name %></h2>

app/views/cats/_form.html.erb
<% cat = @cat ? @cat : Cat.new %>

<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action="<%= action_url %>" method="post">

  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">

  <br>

  <label for="birth-date">Birth Date</label>
  <input id="birth-date" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>

  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option disabled <%= cat.color ? "" : "selected" %>>--Please Select--</option>
    <option value="Orange" <%= cat.color == "Orange" ? "selected" : "" %>>Orange</option>
    <option value="Orange">Orange</option>
    <option value="Black" <%= cat.color == "Black" ? "selected" : "" %>>Black</option>
    <option value="White" <%= cat.color == "White" ? "selected" : "" %>>White</option>
    <option value="Brown" <%= cat.color == "Brown" ? "selected" : "" %>>Brown</option>
    <option value="Calico" <%= cat.color == "Calico" ? "selected" : "" %>>Calico</option>
    <option value="Grey" <%= cat.color == "Grey" ? "selected" : "" %>>Grey</option>
  </select>

  <br>

  <label for="sex">Sex</label> <br>
  <input id="sex" type="radio" name="cat[sex]" value="M" <%= cat.sex == 'M' ? "checked" : "" %> > Male <br>
  <input id="sex" type="radio" name="cat[sex]" value="F" <%= cat.sex == 'F' ? "checked" : "" %> > Female <br>

  <br>

  <label for="description">Description <br>
    <textarea name="cat[description]" rows="8" cols="80"><%= cat.description %></textarea>
  </label>

  <br>

  <% if cat.persisted? %>
    <%= button_to 'Edit Cat', cat_url(cat), method: :patch %>
  <% else %>
    <%= button_to 'Add Cat', cats_url %>
  <% end %>

</form>

app/views/cats/edit.html.erb
<h2>Edit <%= @cat.name %></h2>

<%= render 'form', action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<h1>All Cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li>
      <%= link_to "#{cat.name}", cat_url(cat) %>
      <!-- <%= cat.name %> -->
    </li>
  <% end %>
</ul>

app/views/cats/new.html.erb
<h2>Adopt a Cat!</h2>

<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<h2><%= @cat.name %></h2>

<table>
  <tr>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description ? @cat.description : "" %></td>
  </tr>
</table>

<% @cat.rental_requests.each do |request| %>
  <p>Rental Status : <%= request.status %>  </p>
  <p>Start Date : <%= request.start_date %> </p>
  <p>End Date : <%= request.end_date %> </p>
  <% if request.pending? %>
    <%= button_to 'Approve', approve_cat_rental_request_url(request.id),
        method: :post %>
    <%= button_to 'Deny', deny_cat_rental_request_url(request.id),
        method: :post %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>